name: Release Build

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build:
    name: Build static binary with sound
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка компилятора и зависимостей ALSA
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            upx \
            libasound2-dev \
            gcc-x86-64-linux-gnu \
            pkg-config

      # Настройка переменных окружения
      - name: Setup environment
        run: |
          echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      # Установка Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      # Сборка
      - name: Build release
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/music_player
          upx --best target/x86_64-unknown-linux-musl/release/music_player

      # Создание релиза
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ github.ref_name }}"
          files: |
            target/x86_64-unknown-linux-musl/release/music_player
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}