name: Release Build

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build:
    name: Build static binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка зависимостей
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools upx

      # Явное указание версии Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-unknown-linux-musl
          toolchain: stable  # ← Явно указываем версию
          override: true
          components: rustfmt, clippy  # Опционально

      # Проверка версии
      - name: Check Rust version
        run: rustc --version

      # Сборка
      - name: Build release
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/music_player
          upx --best target/x86_64-unknown-linux-musl/release/music_player

      # Создание релиза
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ github.ref_name }}"
          files: |
            target/x86_64-unknown-linux-musl/release/music_player
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}