name: Release Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    name: Build Static Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка базовых зависимостей
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            musl-tools \
            upx \
            libasound2-dev \
            pkg-config

      # Настройка Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      # Сборка проекта
      - name: Build release
        run: |
          mkdir -p .cargo
          echo '[target.x86_64-unknown-linux-musl]' > .cargo/config.toml
          echo 'linker = "x86_64-linux-gnu-gcc"' >> .cargo/config.toml
          
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/music_player
          upx --best target/x86_64-unknown-linux-musl/release/music_player

      # Создание релиза
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ github.ref_name }}"
          files: |
            target/x86_64-unknown-linux-musl/release/music_player
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}