name: Release Build

on:
  push:
    tags: ["v*"]  # Запускать при создании тега (например, v1.0.0)

jobs:
  build:
    name: Build static binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl]  # Можно добавить другие цели (aarch64, etc.)

    steps:
      - uses: actions/checkout@v4

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Setup Rust (musl)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
          override: true

      - name: Build (release)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Strip binary (уменьшаем размер)
        run: |
          strip ./target/${{ matrix.target }}/release/music_player

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: music_player-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/music_player

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            music_player-*/music_player
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}