name: Release Build

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build:
    name: Build static binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools upx

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Configure linker
        run: |
          mkdir -p .cargo
          echo '[target.x86_64-unknown-linux-musl]' > .cargo/config.toml
          echo 'linker = "x86_64-linux-gnu-gcc"' >> .cargo/config.toml

      - name: Build release
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/music_player
          upx --best target/x86_64-unknown-linux-musl/release/music_player

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ github.ref_name }}"
          files: |
            target/x86_64-unknown-linux-musl/release/music_player